vietnamese_to_english_mapping = {
    'á': 'a',
    'à': 'a',
    'ả': 'a',
    'ã': 'a',
    'ạ': 'a',
    'â': 'a',
    'ấ': 'a',
    'ầ': 'a',
    'ẩ': 'a',
    'ẫ': 'a',
    'ậ': 'a',
    'ă': 'a',
    'ắ': 'a',
    'ằ': 'a',
    'ẳ': 'a',
    'ẵ': 'a',
    'ặ': 'a',
    'é': 'e',
    'è': 'e',
    'ẻ': 'e',
    'ẽ': 'e',
    'ẹ': 'e',
    'ê': 'e',
    'ế': 'e',
    'ề': 'e',
    'ể': 'e',
    'ễ': 'e',
    'ệ': 'e',
    'í': 'i',
    'ì': 'i',
    'ỉ': 'i',
    'ĩ': 'i',
    'ị': 'i',
    'ó': 'o',
    'ò': 'o',
    'ỏ': 'o',
    'õ': 'o',
    'ọ': 'o',
    'ô': 'o',
    'ố': 'o',
    'ồ': 'o',
    'ổ': 'o',
    'ỗ': 'o',
    'ộ': 'o',
    'ơ': 'o',
    'ớ': 'o',
    'ờ': 'o',
    'ở': 'o',
    'ỡ': 'o',
    'ợ': 'o',
    'ú': 'u',
    'ù': 'u',
    'ủ': 'u',
    'ũ': 'u',
    'ụ': 'u',
    'ư': 'u',
    'ứ': 'u',
    'ừ': 'u',
    'ử': 'u',
    'ữ': 'u',
    'ự': 'u',
    'ý': 'y',
    'ỳ': 'y',
    'ỷ': 'y',
    'ỹ': 'y',
    'ỵ': 'y',
}

danh_sach_dai = ("2d","3d","4d","tp","mt","mn",
                "thanh pho", "thanhpho", "thanh.pho", "thpho", "hcm", "tph", "t.ph", "tp", "tphcm", "t.pho", "tpho",
                "dong thap", "dong.thap", "dongthap", "dt", "dth", "dai dong thap", "d.thap", "dthap", "d thap", "d.thap",
                "ca mau", "ca. mau", "camau", "ca.mau", "cm", "cmau", "c mau", "c.mau", "dai ca mau",
                "ben tre", "bentre", "bt", "btr", "btre", "b tre", "b.tre", "dai ben tre",
                "vung tau", "vung. tau", "dung tau", "vungtau", "dungtau", "vug tau", "vt", "vtau", "v tau", "v.tau", "dai vung tau",
                "bac lieu", "bac. lieu", "baclieu", "bac.lieu", "bli", "blie", "bliu", "bl", "b lieu", "blieu", "b.lieu", "dai bac lieu",
                "dong nai", "dong.nai", "dongnai", "dog nai", "dognai", "dn", "dnai", "d.nai", "dai dong nai",
                "can tho", "cantho", "ct", "cth", "dai can tho", "ctho", "c.tho",
                "soc trang", "soctrang", "soc.trang", "soc. trang", "st", "str", "dai soc trang", "strang", "s.trang", "s trang",
                "tay ninh", "tay.ninh", "tayninh", "tninh", "t.ninh", "t.n", "tn", "dai tay ninh",
                "an giang", "angiang", "agiang", "agian", "ag", "a.g", "agiag", "a.giang", "dai an giang",
                "binh thuan", "binh. thuan", "binh.thuan", "binhthuan", "bthuan", "b.thuan", "b thuan", "bth", "bt", "dai binh thuan",
                "vinh long", "vinhlong", "vlong", "vlog", "v.long", "v long", "v.l", "vl", "dai vinh long",
                "binh duong", "binhduong", "bduong", "bduog", "b.duong", "b duong", "b duog", "bdu", "song be", "sbe", "s.be", "sb", "bd", "bdg", "dai binh duong",
                "tra vinh", "tra. vinh", "tra.vinh", "travinh", "trvinh", "trav", "tvinh", "t.vinh", "t vinh", "tv", "t.v", "trv", "dai tra vinh",
                "long an", "log an", "longan", "logan", "long.an", "log.an", "lg.an", "l.an", "lan", "la", "l.a", "dai long an",
                "binh phuoc", "binhphuoc", "binh.phuoc", "binh. phuoc", "bphuoc", "phuoc", "b.phuoc", "bp", "dai binh phuoc",
                "hau giang", "haugiang", "hau.giang", "hau. giang", "hgiang", "h.giang", "hg", "dai hau giang",
                "tien giang", "tien.giang", "tiengiang", "tienggiang", "tgiang", "t giang", "t.giang", "tg", "tgi", "tgiag", "dai tien giang",
                "kien giang", "kieng giang", "kiengiang", "kgiang", "k.giang", "kg", "k.g", "kgi", "dai kien giang",
                "da lat", "da. lat", "da lac", "dalat", "da.lat", "dalac", "da.lac", "dalt", "dal", "dl", "dlat", "d.lat", "dai da lat",
                "phu yen", "phuyen", "phu.yen", "pyen", "py", "p.y", "p yen", "p.yen",
                "thua thien hue", "thu thien hue", "thua t hue", "tth", "th", "tthue", "tt hue", "t.t.hue", "hue",
                "dak lak", "daklak", "daclak", "dac lak", "dac.lak", "dak.lak", "daklac", "dak lac", "dlak", "dlac", "dlat", "dl", "daclac", "dac lac", "dac lat", "dat lac", "dat lak", "d.lak",
                "quang nam", "quan nam", "quangnam", "quang.nam", "qnam", "q.nam", "qn",
                "da nang", "da.nang", "danang", "da nag", "da.nag", "danag", "dnang", "dnag", "dna", "d nang", "d.nang", "dng", "dn",
                "khanh hoa", "khanh.hoa", "khanhhoa", "khahhoa", "khoa", "kha", "kh,hoa", "k.hoa", "k,hoa", "k hoa", "kh hoa", "kh",
                "binh dinh", "binh. dinh", "binh.dinh", "binhdinh", "bdinh", "b dinh", "b.dinh", "bdi", "bd",
                "quang tri", "quang. tri", "quan tri", "quangtri", "quang.tri", "qt", "qtri", "q.tri", "qtr",
                "quang binh", "quan binh", "quangbinh", "quang.binh", "qb", "qbinh", "q binh", "q.binh", "qbi",
                "gja laj", "gia lai", "gia.lai", "gialai", "gjalaj", "gl", "glai", "g.lai", "gla",
                "ninh thuan", "ninh.thuan", "ninhthuan", "nt", "nthuan", "n.thuan", "nth",
                "quang ngai", "quang.ngai", "quangngai", "quan ngai", "quan.ngai", "quanngai", "qngai", "q ngai", "q.ngai", "qng", "qn",
                "dak nong", "dac nong", "daknong", "dacnong", "dkn", "dnong", "dno", "d.nong",
                "ktum", "kontum", "kontom", "komtum", "kumtum", "kuntum", "kon", "ktun", "ktu", "kt")

dais = ["2d","3d","4d","tp","mt","mn",
        "thanh pho", "thanhpho", "thanh.pho", "thpho", "hcm", "tph", "t.ph", "tp", "tphcm", "t.pho", "tpho",
        "dong thap", "dong.thap", "dongthap", "dt", "dth", "dai dong thap", "d.thap", "dthap", "d thap", "d.thap",
        "ca mau", "ca. mau", "camau", "ca.mau", "cm", "cmau", "c mau", "c.mau", "dai ca mau",
        "ben tre", "bentre", "bt", "btr", "btre", "b tre", "b.tre", "dai ben tre",
        "vung tau", "vung. tau", "dung tau", "vungtau", "dungtau", "vug tau", "vt", "vtau", "v tau", "v.tau", "dai vung tau",
        "bac lieu", "bac. lieu", "baclieu", "bac.lieu", "bli", "blie", "bliu", "bl", "b lieu", "blieu", "b.lieu", "dai bac lieu",
        "dong nai", "dong.nai", "dongnai", "dog nai", "dognai", "dn", "dnai", "d.nai", "dai dong nai",
        "can tho", "cantho", "ct", "cth", "dai can tho", "ctho", "c.tho",
        "soc trang", "soctrang", "soc.trang", "soc. trang", "st", "str", "dai soc trang", "strang", "s.trang", "s trang",
        "tay ninh", "tay.ninh", "tayninh", "tninh", "t.ninh", "t.n", "tn", "dai tay ninh",
        "an giang", "angiang", "agiang", "agian", "ag", "a.g", "agiag", "a.giang", "dai an giang",
        "binh thuan", "binh. thuan", "binh.thuan", "binhthuan", "bthuan", "b.thuan", "b thuan", "bth", "bt", "dai binh thuan",
        "vinh long", "vinhlong", "vlong", "vlog", "v.long", "v long", "v.l", "vl", "dai vinh long",
        "binh duong", "binhduong", "bduong", "bduog", "b.duong", "b duong", "b duog", "bdu", "song be", "sbe", "s.be", "sb", "bd", "bdg", "dai binh duong",
        "tra vinh", "tra. vinh", "tra.vinh", "travinh", "trvinh", "trav", "tvinh", "t.vinh", "t vinh", "tv", "t.v", "trv", "dai tra vinh",
        "long an", "log an", "longan", "logan", "long.an", "log.an", "lg.an", "l.an", "lan", "la", "l.a", "dai long an",
        "binh phuoc", "binhphuoc", "binh.phuoc", "binh. phuoc", "bphuoc", "phuoc", "b.phuoc", "bp", "dai binh phuoc",
        "hau giang", "haugiang", "hau.giang", "hau. giang", "hgiang", "h.giang", "hg", "dai hau giang",
        "tien giang", "tien.giang", "tiengiang", "tienggiang", "tgiang", "t giang", "t.giang", "tg", "tgi", "tgiag", "dai tien giang",
        "kien giang", "kieng giang", "kiengiang", "kgiang", "k.giang", "kg", "k.g", "kgi", "dai kien giang",
        "da lat", "da. lat", "da lac", "dalat", "da.lat", "dalac", "da.lac", "dalt", "dal", "dl", "dlat", "d.lat", "dai da lat",
        "phu yen", "phuyen", "phu.yen", "pyen", "py", "p.y", "p yen", "p.yen",
        "thua thien hue", "thu thien hue", "thua t hue", "tth", "th", "tthue", "tt hue", "t.t.hue", "hue",
        "dak lak", "daklak", "daclak", "dac lak", "dac.lak", "dak.lak", "daklac", "dak lac", "dlak", "dlac", "dlat", "dl", "daclac", "dac lac", "dac lat", "dat lac", "dat lak", "d.lak",
        "quang nam", "quan nam", "quangnam", "quang.nam", "qnam", "q.nam", "qn",
        "da nang", "da.nang", "danang", "da nag", "da.nag", "danag", "dnang", "dnag", "dna", "d nang", "d.nang", "dng", "dn",
        "khanh hoa", "khanh.hoa", "khanhhoa", "khahhoa", "khoa", "kha", "kh,hoa", "k.hoa", "k,hoa", "k hoa", "kh hoa", "kh",
        "binh dinh", "binh. dinh", "binh.dinh", "binhdinh", "bdinh", "b dinh", "b.dinh", "bdi", "bd",
        "quang tri", "quang. tri", "quan tri", "quangtri", "quang.tri", "qt", "qtri", "q.tri", "qtr",
        "quang binh", "quan binh", "quangbinh", "quang.binh", "qb", "qbinh", "q binh", "q.binh", "qbi",
        "gja laj", "gia lai", "gia.lai", "gialai", "gjalaj", "gl", "glai", "g.lai", "gla",
        "ninh thuan", "ninh.thuan", "ninhthuan", "nt", "nthuan", "n.thuan", "nth",
        "quang ngai", "quang.ngai", "quangngai", "quan ngai", "quan.ngai", "quanngai", "qngai", "q ngai", "q.ngai", "qng", "qn",
        "dak nong", "dac nong", "daknong", "dacnong", "dkn", "dnong", "dno", "d.nong",
        "ktum", "kontum", "kontom", "komtum", "kumtum", "kuntum", "kon", "ktun", "ktu", "kt"]


